name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # каждые 12 часов
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: udkx
          svg_out_path: github-contribution-grid-snake.svg
          snake_color: '#7A95C9'
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: . # в тукущую директорию
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
